### PR TITLE
Add support for Stata

### PR DESCRIPTION
**Pull request by richardcherron**
Stata documentation: https://www.stata.com/manuals13/pcomments.pdf

'//%s' works as a linewise comment, too, but only in .do scripts. If you copy-and-paste a '//%s' comment into the console, it generates an error.

### CODE REVIEW

**Comment by numToStr** [comment]
Is this language already supported by (n)vim? Like syntax highlighting and stuff.

**Comment by richardcherron** [comment]
Nvim provides Stata highlighting by default, and `gcc` comments linewise with `/*%s*/`. For example, the following code
```{stata}
sysuse auto, clear
summarize
```
becomes
```{stata}
/* sysuse auto, clear */
/* summarize */
```
However, it would be better if `gcc` commented linewise with `*%s`, yielding
```{stata}
* sysuse auto, clear
* summarize
```
because Stata's console accepts `*%s` comments but rejects (errors) `/*%s*/`comments.

Please let me know if there is a better way to achieve this behavior or submit this pull request. Thanks!

**Comment by numToStr** [comment]
> Nvim provides Stata highlighting by default

Nice.

> because Stata's console accepts *%s comments but rejects (errors) /*%s*/comments.

IIUC, `*%s` is not valid for trailing comments which means `gcA` mapping will be useless whereas `//%s` will work for all (line comment) cases.

**Comment by richardcherron** [comment]
Ah! I rarely use `gcA`, so I had not considered this case. Instead, I use `A//`. `//%s` works as a trailing comment but fails in the console. 

| Character | Mode | Works in console? | Works as trailing comment? |
| --- | --- | --- | --- |
| `*%s` | Linewise | Yes | No |
| `//%s` | Linewise | No | Yes |
| `/*%s*/` | Blockwise | No | NA |

Stata's comment characters and mixed console/script usage make a perfect solution difficult. I frequently copy-and-paste several lines of code into Stata's console, so I prefer `*%s` to `//%s`. However, someone who runs full scripts (and never copies-and-pastes) might prefer `//%s`.

**Comment by numToStr** [comment]
`/*%s*/` can be used as trailing comment as per docs. In any case, i would much prefer to have `//%s` and `/*%s*/` for line and block comments respectively.

But, you would loose console support. IDK anything about stata, so I would let you decide.

**Comment by richardcherron** [comment]
You're right, and `//%s` and `/*%s*/` are better linewise and clockwise comments, respectively. I checked Stata's built-in editor, and it uses `//%s` comments. I shouldn't break what Stata and Comment.nvim users expect because of my workflow. I updated my branch's ft.lua.

Thanks for the help and a great package!

**Review by numToStr — APPROVED** [review]
Thanks 👍

**Pull request merged**
