### PR TITLE
Fallback to linewise ctype when no right comment string

### LINKED ISSUE #275: Use linewise instead of blockwise comments for languages that don't support block comments
## Description

Languages such as Python and Bash don't support block comments. This results in undesirable behaviour when attempting to (un)comment blockwise using Comment.nvim; the linewise comment string is used as a fallback and inserted or removed at the start of the comment block, affecting only the first line of the block.

## Example

The following is Python code with the pipe representing the position of the Neovim cursor in normal mode.

```python
a = |1
b = 2
c = 3
```

If I were to press `gb2j`, the following would be observed.

```python
# a |= 1
b = 2
c = 3
```

While I would expect the following behaviour.

```python
# a |= 1
# b = 2
# c = 3
```

## Motivation

I'm aware that the workaround is to simply use linewise comment blocks in these files. However, I prefer to use blockwise comments for comment blocks and remembering to use a different keymap for these languages is avoidable mental overhead. I'm also quite certain that the current behaviour is not desired or expected by the majority of users.

### PR DESCRIPTION
**Pull request by emileferreira**
This resolves #275.

### CODE REVIEW

**Comment by numToStr** [comment]
No, this is unexpected behaviour IMO. You just don't fallback to a completely different thing. Blockwise and linewise are separated for a reason. If you want this behaviour, I would suggest you to make a custom keybindings.

**Comment by emileferreira** [comment]
While I agree that the suggested behaviour may be surprising at first, I consider the current behaviour to be a bug; the user expects the specified lines to be un(commented) but only the first line is affected. This is never what the user wanted unless only one line, or part thereof, is specified - in which case it will behave in the same way as my suggestion. The suggested behaviour of falling back to linewise comments for languages that don't support comment blocks would be well-documented and could be toggled with a config flag.

If you're still not convinced, I could make another pull request that changes the current behaviour to do nothing and display a warning stating that block comments are not supported in the current language. I would consider this preferable to attempting to make a blockwise comment with a linewise comment string and failing.

**Comment by emileferreira** [comment]
> You just don't fallback to a completely different thing. Blockwise and linewise are separated for a reason.

Linewise comments on subsets of a line use blockwise comment strings. For example, `gcw` and `gbw` are equivalent.

**Comment by numToStr** [comment]
> > You just don't fallback to a completely different thing. Blockwise and linewise are separated for a reason.
> 
> Linewise comments on subsets of a line use blockwise comment strings. For example, `gcw` and `gbw` are equivalent.

Yes, I admit that's one intersection b/w blockwise and linewise, and that's because of https://github.com/tomtom/tcomment_vim, from which i ported the behaviour. 

> display a warning stating that block comments are not supported in the current language.

💯. I am in complete favour of this.

**Comment by renxzen** [comment]
> If you want this behaviour, I would suggest you to make a custom keybindings.

Could you help me in making this keybinding? Currently what i have is:

```
vim.keymap.set("v", "<leader>/", function()
	vim.api.nvim_feedkeys(vim.api.nvim_replace_termcodes("<esc>", false, true, true), "nx", false)

	local blockwise = require("Comment.api").toggle.blockwise(vim.fn.visualmode())
	local ok = pcall(blockwise)
	if not ok then
	 	require("Comment.api").toggle.linewise(vim.fn.visualmode())
	end
end, noremap)

```

but the current behaviour is that what's inside the if block always runs, since aparently either if i get the error
`[Comment.nvim] python doesn't support block comments!` or not, error `attempt to call a nil value` always returns from the pcall.

**Comment by benedikt-bartscher** [comment]
@renxzen did you find a solution to catch those errors and fallback too linewise?

**Comment by benedikt-bartscher** [comment]
@renxzen I found a way to fallback on errors

```lua
    vim.keymap.set({ 'x', 'n' }, '<leader>c', function()
      vim.api.nvim_feedkeys(esc, 'nx', false)
      -- If the blockwise toggle fails fallback to linewise (e.g. for python which has no blockwise comments)
      local err = vim.fn.execute 'lua require("Comment.api").toggle.blockwise(vim.fn.visualmode())'
      if err:find 'Comment.nvim' then
        -- Try to toggle linewise instead
        api.toggle.linewise(vim.fn.visualmode())
      end
    end, { desc = 'Toggle [C]omment', silent = true })
```

**Pull request closed without merging**
