### PR TITLE
feat!: reimplement lua api 🎉 

### LINKED ISSUE #78: API availability and mappings
Is there a reason some API methods are only available when some mappings are enabled? I guess many people (myself included) will use the API to define their own custom key mappings. It would be nice if one could disable all mappings and yet be able to use all API methods.

### PR DESCRIPTION
**Pull request by numToStr**
Closes #78 

---

This time it's in a good shape.

### CODE REVIEW

**Comment by numToStr** [comment]
API migration

```lua
require('Comment.api').{toggle => toggleln_linewise}()
require('Comment.api').{comment => commentln_linewise}()
require('Comment.api').{uncomment => uncommentln_linewise}()
require('Comment.api').{gcc => toggleln_linewise}()
require('Comment.api').{gbc => toggleln_blockwise}()
require('Comment.api').{gc => toggle_linewise_op}()
require('Comment.api').{gb => toggle_blockwise_op}()
require('Comment.api').{gco => insert_linewise_below}()
require('Comment.api').{gcO => insert_linewise_above}()
require('Comment.api').{gcA => insert_linewise_eol}()
```

**Comment by clason** [comment]
Looks good, especially since it seems to remove duplicate API?

Only suggestion would be to drop the `ln` from the first five -- that looks redundant.

**Comment by numToStr** [comment]
> especially since it seems to remove duplicate API?

Quite the opposite ;)


> Only suggestion would be to drop the `ln` from the first five -- that looks redundant. 

I have three variant such as

```lua
toggleln_linewise() -- current line but no dot-repeat
toggleln_linewise_op() -- current line + dot-repeat
toggle_linewise_op() -- multiple line + dot-repeat
```

If I remove `ln` then 

```lua
toggle_linewise() -- current line but no dot-repeat
toggle_linewise_op() -- multiple line + dot-repeat
```

**Comment by clason** [comment]
Oh, I see. I thought the list above was complete.

May I then suggest `toggle_single` instead of `toggleln`? I think that's clearer.

**Comment by numToStr** [comment]
> May I then suggest `toggle_single` instead of `toggleln`? I think that's clearer.

Ahh, yes. I can change that. Thanks!

(those names are getting longer haha)

**Comment by numToStr** [comment]
@clason I've changed `ln` to `current`. I think it's more clear than `single` ;)

**Pull request merged**
