### PR TITLE
feat: add `lisp` support

### PR DESCRIPTION
**Pull request by mvllow**
includes fennel, lisp and scheme filetypes

### CODE REVIEW

**Comment by numToStr** [comment]
Does lisp comments starts with one comma? Although I have also seen two commas like in treesitter queries.

(I am not a lisp guy, so i might be missing something)

**Comment by mvllow** [comment]
didn't even think of that, i saw that `;` worked but you're right, `;;` is the proper convention when commenting code 😌

**Comment by numToStr** [comment]
Noice. Also can you check the filetype for treesitter queries? We can also add that if it's different from `lisp`.

**Comment by numToStr** [comment]
@mvllow I did a quick read and I think `scheme` also supports block comments.

From scheme docs:

> Block comments are delimited by #| and |# pairs, and may be nested.

**Comment by mvllow** [comment]
added block comments to lisp and scheme. fennel doesn't seem to have block comments

**Comment by mvllow** [comment]
closure may have the same lisp comments as well, although i haven't tried it

**Comment by mvllow** [comment]
built-in clojure's commentstring is `;`. should we override that to match `;;`? still seems like `;;` is more conventional – although `;` _works_ for all of the mentioned lisp languages

**Comment by numToStr** [comment]
For now I think it's ok. We can add closure in a separate PR or if someone complains about it :)

**Pull request merged**
