### PR TITLE
feat!: `<Plug>` mappings

### LINKED ISSUE #96: Expose `<Plug>` mappings
> I can't do much about it. You'll still need to know a little about how VISUAL mode works. Also, we can mention this in docs :)

My mappings with Kommentay were like this:

```lua
local map = require'map'
map.n{'<leader>c', '<Plug>kommentary_line_default', noremap = false}
map.x{'<leader>c', '<Plug>kommentary_visual_default<C-c>', noremap = false}
```
I don't know what it's going on under the hood. I wonder if it's something that could be applied here as well?

_Originally posted by @mbenford in https://github.com/numToStr/Comment.nvim/issues/78#issuecomment-992833436_

### PR DESCRIPTION
**Pull request by numToStr**
I think these are nice to have and I am only planning to add `<Plug>`s for basic mappings.

Closes #96

### CODE REVIEW

**Comment by numToStr** [comment]
As this is using `vim.keymap.set`, I am going to merge this after the 0.7.0 release.

**Comment by numToStr** [comment]
Note to myself: make sure to update the API.md

**Comment by melkster** [comment]
> As this is using vim.keymap.set, I am going to merge this after the 0.7.0 release.

@numToStr Here's a friendly reminder that 0.7 has been relased :)

**Comment by numToStr** [comment]
@melkster I am aware of that. I just need to update the docs, so maybe I'll merge this later today or tomorrow :)

(Also need to tag a release, so that 0.6 users won't come at me with guns blazing)

**Comment by numToStr** [comment]
Tag is up https://github.com/numToStr/Comment.nvim/releases/tag/v0.6

**Pull request merged**
