### PR TITLE
add comment to latex

### PR DESCRIPTION
**Pull request by aspeddro**

### CODE REVIEW

**Review by numToStr — APPROVED** [review]
Thanks 👍🏻

**Comment by clason** [comment]
Note that `%` is _not_ a comment string in BibTeX. (In fact, the BibTeX syntax doesn't _have_ comments....)

Also, Vim uses `tex` for LaTeX files and `plaintex` for plain TeX files -- changing this can lead to confusion (and in fact I don't see why this PR was necessary; comment.nvim worked fine with (La)TeX files before...)

**Comment by clason** [comment]
_And_ I much prefer the default `% %s` (with the space). (You sometimes see `%%` comments, but only in class and style files.)

**Comment by aspeddro** [comment]
@clason you're right. 

#75

**Pull request merged**
