### PR TITLE
Add rego support (simple hash)

### PR DESCRIPTION
**Pull request by cova-fe**

### CODE REVIEW

**Comment by numToStr** [comment]
Thanks for the PR! Although I have to say that I've never heard of `rego`. So obviously my question is does rego is supported by (n)vim OOTB? Also, a link to its comment syntax doc would be nice :)

**Comment by cova-fe** [comment]
I added the link to the language itself (it is used in open policy agent) to commit text.
Regarding (n)vim support, out of the box vim uses /* */ comment structure, that does not fit with language, as can be seen here:
https://www.openpolicyagent.org/docs/latest/policy-language/#comments

**Comment by numToStr** [comment]
> Regarding (n)vim support, out of the box vim uses /* */ comment structure, that does not fit with language

Because it might be using the default commentstring which is `/* */`. Also does vim has highlighting for rego?

**Comment by cova-fe** [comment]
> > Regarding (n)vim support, out of the box vim uses /* */ comment structure, that does not fit with language
> 
> Because it might be using the default commentstring which is `/* */`. Also does vim has highlighting for rego?

You can have support via treesitter (FallenAngel97/tree-sitter-rego). Not sure if this answers your question though.
(I'm using lunarvim "custom" nvim )

**Comment by numToStr** [comment]
> FallenAngel97/tree-sitter-rego

That's more than enough :)

**Pull request merged**
