### PR TITLE
fix: empty line indentation when using tabs

### LINKED ISSUE #225: wrong indent comment on empty line with tabs
image
when i multi select  the lines with empty line and `line-comment` then comment on empty line don't follows the indent. 
this happens with c/c++ file.

### PR DESCRIPTION
**Pull request by numToStr**
Fixes #225

### CODE REVIEW

**Comment by numToStr** [comment]
@shaeinst Does this fixes your issue?

**Comment by shaeinst** [comment]
@numToStr just tried but i'm afraid it didn't work. i am still getting the comment on the start of empty line
image

**Comment by numToStr** [comment]
Are you sure you are using `tabs` branch? I tested with go files and it worked for me.

**Comment by shaeinst** [comment]
sorry.. let me test with tab branch

**Comment by shaeinst** [comment]
great, it's working. thanks

**Pull request merged**
