### PR TITLE
fix(opfunc): should save visual mark

### PR DESCRIPTION
**Pull request by kevinhwang91**
nvim_buf_set_lines destroy the visual mark

### CODE REVIEW

**Comment by numToStr** [comment]
I am aware of `nvim_buf_set_lines` destroys marks, not only visual but also user marks i.e. `m{char}`.

You can use `lockmarks` and the plugin exposes a helper function. These technique already used by the default keybindings.

```lua
require('Comment.api').locked('toggle.linewise')(vim.fn.visualmode())
```
is same as

```vim
lockmarks lua require('Comment.api').toggle.linewise(vim.fn.visualmode())
```

> (I wish we had lua api for `lockmarks` with callback support)

**Comment by numToStr** [comment]
See #24 #52

**Comment by kevinhwang91** [comment]
Thanks, it works. Don't know why this API is under API.md

**Comment by numToStr** [comment]
Ahh, I might've missed that. Anyways `:help` docs are coming #205 :)

**Pull request closed without merging**
