### PR TITLE
feat: add `nu` support

### PR DESCRIPTION
**Pull request by jgollenz**
In case you never heard of it: [Nushell](https://www.nushell.sh/book/scripts.html)

### CODE REVIEW

**Comment by jgollenz** [comment]
@numToStr do you have any criteria for adding languages to this plugin? I see some missing from the list, but you might consider them not popular enough.

**Comment by numToStr** [comment]
> do you have any criteria for adding languages to this plugin?

I generally look for if vim has native syntax highlighting, a famous community plugin for highlights, or a tree-sitter parser. If the filetype has any of those then it's good to go.

I know about nushell though, but being a new shell I don't know if there is any highlighting support as of now.

**Comment by jgollenz** [comment]
Thanks for clarifying :+1: 
As far as nushell is concerned, I wouldn't say famous, but a [plugin](https://github.com/LhKipp/nvim-nu) (plus [grammar](https://github.com/LhKipp/tree-sitter-nu)) exists.

**Comment by numToStr** [comment]
> (plus grammar)

That's good to know. Can it be installed via `TSInstall`? Or does it require some config?

**Review by numToStr — APPROVED** [review]

**Comment by jgollenz** [comment]
Unfortunately it is not yet part of the grammars available through the nvim-treesitter repo. However, the nvim-nu plugin [takes care of that](https://github.com/LhKipp/nvim-nu/blob/3ef01939989f4d45520873fdac23a2cd7c9c226b/lua/nu/tree_sitter_config.lua) in the background. Once the plugin is [installed](https://github.com/LhKipp/nvim-nu#installation), `TSInstall nu` will download and setup the nu grammar.

**Comment by numToStr** [comment]
Understood. And looking at the parser repo, i believe it's broken for newer nushell version. Well I hope someday it'd get fixed and upstreamed to `nvim-treesitter` :)

**Comment by jgollenz** [comment]
> it's broken for newer nushell version

Unfortunately, yes :( I understand if you want to wait with this PR until it is up-to-date.

**Pull request merged**
